-- Seed the 8 target cities with full SEO content
INSERT INTO public.cities (name, slug, department, postal_code, lat, lng, hero_title, hero_subtitle, intro_paragraph, local_context, faq_answer, meta_title, meta_description, is_active)
VALUES
(
  'Gardanne',
  'gardanne',
  'Bouches-du-Rhône',
  '13120',
  43.4558,
  5.4722,
  'Nous créons votre présence digitale à Gardanne.',
  'Design UI/UX, développement web et solutions e-commerce sur mesure pour les entreprises gardennoises.',
  'C''est à Gardanne, au cœur du bassin minier reconverti en pôle d''activités dynamique, qu''est née l''Agence HDS. Nous connaissons intimement le tissu économique local : des TPE du secteur industriel aux commerces du centre-ville, en passant par les professions libérales installées dans la métropole Aix-Marseille. Cette proximité nous permet de répondre avec précision aux enjeux digitaux des entreprises gardennoises, avec des solutions concrètes et un accompagnement humain sur le long terme.',
  'Gardanne et son bassin concentrent un tissu de PME et d''artisans en pleine mutation numérique. Entre le pôle d''activités de la Palun, les entreprises liées à l''industrie alumine et les commerces du centre, de nombreuses structures ont besoin d''une présence digitale à la hauteur de leur savoir-faire local.',
  'Oui, l''Agence HDS est basée à Gardanne (13120). Nous intervenons chez nos clients gardennois en présentiel, et accompagnons les entreprises du bassin minier, de la zone de la Palun et de tout le secteur Gardanne-Bouc-Bel-Air dans leurs projets digitaux.',
  'Agence Web Gardanne — Création Site Internet | Agence HDS',
  'Agence web basée à Gardanne (13120). Création de sites internet, applications web et e-commerce sur mesure. Devis gratuit — Agence HDS.',
  true
),
(
  'Aix-en-Provence',
  'aix-en-provence',
  'Bouches-du-Rhône',
  '13100',
  43.5297,
  5.4474,
  'Nous créons votre présence digitale à Aix-en-Provence.',
  'Design UI/UX, développement web et solutions SaaS sur mesure pour les entreprises et startups du Pays Aixois.',
  'Aix-en-Provence est l''une des métropoles les plus dynamiques du sud de la France, portée par un écosystème mêlant startups tech, cabinets de conseil, professions libérales et entreprises patrimoniales. Depuis notre base de Gardanne, à quelques minutes du centre aixois, l''Agence HDS accompagne les entreprises aix-en-provençales dans leur transformation digitale depuis plus de 12 ans. Nous combinons la rigueur d''un développement technique moderne — Next.js, Supabase, solutions IA — avec une compréhension fine des attentes du marché local.',
  'Le Pays Aixois concentre un tissu dense de PME innovantes, de professions libérales (avocats, médecins, architectes) et de structures liées à l''enseignement supérieur. Ces entreprises ont des besoins digitaux précis : sites vitrine premium, plateformes de gestion interne, outils de réservation ou d''automatisation. C''est exactement ce que nous construisons.',
  'Oui, l''Agence HDS intervient à Aix-en-Provence et dans tout le Pays Aixois. Basés à Gardanne à 10 minutes du centre-ville d''Aix, nous proposons des rendez-vous en présentiel et accompagnons les entreprises aix-en-provençales de la conception au déploiement.',
  'Agence Web Aix-en-Provence — Création Site Internet | Agence HDS',
  'Agence web à Aix-en-Provence. Création de sites internet, applications web sur mesure et SEO. Stack Next.js + Supabase. Devis gratuit — Agence HDS.',
  true
),
(
  'Marseille',
  'marseille',
  'Bouches-du-Rhône',
  '13000',
  43.2965,
  5.3698,
  'Nous créons votre présence digitale à Marseille.',
  'Développement web, e-commerce et solutions IA pour les entreprises marseillaises qui veulent passer à la vitesse supérieure.',
  'Deuxième ville de France, Marseille est un hub économique méditerranéen en pleine effervescence. Entre la French Tech Aix-Marseille, les entreprises du port et du secteur logistique, les commerces des quartiers et les acteurs du tourisme, la ville concentre une diversité de besoins digitaux que nous maîtrisons parfaitement. L''Agence HDS accompagne les entreprises marseillaises avec des solutions web modernes, performantes et adaptées à leurs enjeux métier — sans les tarifs gonflés des grandes agences parisiennes.',
  'Marseille abrite un tissu entrepreneurial dense et diversifié : startups de la French Tech, PME du secteur maritime et logistique, restaurateurs, hôteliers, professions de santé et commerces de proximité. Tous ont besoin d''une vitrine digitale ou d''outils web qui reflètent leur niveau d''exigence et génèrent des résultats concrets.',
  'Oui, l''Agence HDS intervient à Marseille et dans toute la métropole Aix-Marseille-Provence. Nous nous déplaçons chez nos clients marseillais pour les réunions de lancement et de validation, et assurons un suivi à distance pour le reste du projet.',
  'Agence Web Marseille — Création Site Internet | Agence HDS',
  'Agence web à Marseille. Sites internet, applications web sur mesure, e-commerce et SEO. Tarifs transparents, stack moderne. Devis gratuit — Agence HDS.',
  true
),
(
  'Aubagne',
  'aubagne',
  'Bouches-du-Rhône',
  '13400',
  43.2954,
  5.5675,
  'Nous créons votre présence digitale à Aubagne.',
  'Sites internet, applications web et e-commerce sur mesure pour les artisans, commerçants et PME d''Aubagne.',
  'Aubagne, ville d''artisans et de savoir-faire, est une cité en pleine mutation digitale. Entre la zone industrielle des Paluds — l''une des plus importantes de la région PACA — et un centre-ville commerçant vivant, les entreprises aubagnaises ont besoin de partenaires digitaux qui comprennent leurs réalités. L''Agence HDS conçoit des solutions web taillées pour les TPE et PME locales : sites vitrines efficaces, boutiques e-commerce performantes et outils de gestion sur mesure, le tout avec un accompagnement direct et sans intermédiaire.',
  'La zone des Paluds à Aubagne regroupe plusieurs centaines d''entreprises industrielles et artisanales qui ont souvent une présence digitale insuffisante par rapport à leur niveau d''expertise métier. Nous aidons ces structures à construire une image en ligne à la hauteur de leur savoir-faire.',
  'Oui, l''Agence HDS intervient à Aubagne et dans le secteur de l''Huveaune. Nous accompagnons aussi bien les artisans du centre-ville que les PME de la zone des Paluds dans leurs projets de création ou refonte de site web.',
  'Agence Web Aubagne — Création Site Internet | Agence HDS',
  'Agence web à Aubagne. Création de sites internet sur mesure pour artisans, commerçants et PME. Stack moderne, tarifs clairs. Devis gratuit — Agence HDS.',
  true
),
(
  'Vitrolles',
  'vitrolles',
  'Bouches-du-Rhône',
  '13127',
  43.4617,
  5.2481,
  'Nous créons votre présence digitale à Vitrolles.',
  'Solutions web performantes pour les entreprises de la zone de Vitrolles et du bassin de l''Étang de Berre.',
  'Vitrolles est l''une des principales zones d''activités économiques de la métropole Aix-Marseille, portée par sa proximité avec l''aéroport Marseille-Provence et son parc d''activités Aéropole. Les entreprises qui s''y installent ont des profils variés — logistique, services aux entreprises, high-tech, aéronautique — et des besoins digitaux souvent complexes. L''Agence HDS conçoit des plateformes web, des applications métier et des outils SaaS adaptés à ces environnements exigeants, avec une architecture technique robuste et scalable.',
  'Le bassin de Vitrolles et de l''Étang de Berre concentre un tissu industriel et logistique important, avec des entreprises qui ont besoin d''outils digitaux sur mesure : extranets clients, plateformes de gestion, sites B2B. C''est une spécialité de l''Agence HDS.',
  'Oui, l''Agence HDS intervient à Vitrolles et dans tout le bassin de l''Étang de Berre. Nous accompagnons les entreprises de l''Aéropole et des zones d''activités environnantes dans leurs projets digitaux, du site vitrine à l''application web sur mesure.',
  'Agence Web Vitrolles — Création Site Internet | Agence HDS',
  'Agence web à Vitrolles. Sites internet, applications web B2B et solutions SaaS pour les entreprises de l''Aéropole. Devis gratuit — Agence HDS.',
  true
),
(
  'Martigues',
  'martigues',
  'Bouches-du-Rhône',
  '13500',
  43.4046,
  5.0486,
  'Nous créons votre présence digitale à Martigues.',
  'Design web, e-commerce et applications sur mesure pour les entreprises et commerçants de Martigues.',
  'Surnommée la Venise Provençale, Martigues est une ville où le tourisme, la pêche traditionnelle et l''industrie pétrochimique cohabitent dans un équilibre unique. Ce mélange crée des besoins digitaux très variés : sites de réservation pour les activités touristiques, boutiques e-commerce pour l''artisanat local, outils de communication pour les entreprises industrielles du bassin de Fos. L''Agence HDS maîtrise ces différents univers et livre des solutions web sur mesure qui parlent à chaque cible.',
  'Martigues et le pourtour de l''Étang de Berre concentrent des secteurs économiques très différents : industrie lourde, tourisme lacustre, commerce de proximité et artisanat. Cette diversité se traduit par des besoins digitaux spécifiques que nous savons adresser avec précision.',
  'Oui, l''Agence HDS intervient à Martigues et dans le secteur de l''Étang de Berre. Nous accompagnons aussi bien les commerçants du quai Brescon que les entreprises industrielles de la zone de Fos-sur-Mer.',
  'Agence Web Martigues — Création Site Internet | Agence HDS',
  'Agence web à Martigues. Sites internet, e-commerce et applications web sur mesure pour entreprises et commerçants. Devis gratuit — Agence HDS.',
  true
),
(
  'Salon-de-Provence',
  'salon-de-provence',
  'Bouches-du-Rhône',
  '13300',
  43.6403,
  5.0972,
  'Nous créons votre présence digitale à Salon-de-Provence.',
  'Création de sites internet et solutions digitales pour les entreprises et commerçants de Salon-de-Provence.',
  'Salon-de-Provence, ville carrefour entre Aix, Arles et Avignon, est un bassin économique structuré autour du commerce, des services et de la Base aérienne 701. Les entreprises salonaises ont souvent besoin d''une présence web plus solide pour capter des clients sur une zone de chalandise élargie. L''Agence HDS conçoit des sites internet et des stratégies digitales pensées pour générer des résultats concrets : plus de visibilité sur Google, plus de contacts entrants, plus de ventes en ligne.',
  'Salon-de-Provence réunit un tissu de PME, d''artisans et de commerçants avec un fort ancrage local mais un rayonnement qui dépasse souvent la ville. Nos solutions SEO et web sont conçues pour leur permettre de capter des prospects sur l''ensemble du bassin de vie salonais.',
  'Oui, l''Agence HDS intervient à Salon-de-Provence et dans le secteur de la Crau. Nous nous déplaçons chez nos clients salonais pour les réunions clés et assurons un suivi régulier tout au long du projet.',
  'Agence Web Salon-de-Provence — Création Site Internet | Agence HDS',
  'Agence web à Salon-de-Provence. Création de sites internet, SEO et applications web sur mesure. Accompagnement personnalisé. Devis gratuit — Agence HDS.',
  true
),
(
  'La Ciotat',
  'la-ciotat',
  'Bouches-du-Rhône',
  '13600',
  43.1743,
  5.6044,
  'Nous créons votre présence digitale à La Ciotat.',
  'Sites internet, e-commerce et solutions digitales pour les entreprises, nautisme et tourisme de La Ciotat.',
  'La Ciotat, ville berceau du cinéma et capitale provençale du nautisme de plaisance, attire chaque année des milliers de visiteurs et concentre un tissu d''entreprises unique autour des chantiers navals, du tourisme littoral et du commerce local. L''Agence HDS accompagne les acteurs économiques ciotadens dans leur présence en ligne : sites vitrine élégants pour les prestataires touristiques, boutiques e-commerce pour l''artisanat local, plateformes de réservation pour les activités nautiques et outils de gestion pour les professionnels du port.',
  'La Ciotat combine une économie touristique saisonnière forte et un tissu d''entreprises permanentes dans le nautisme, la réparation navale et les services. Ces deux univers nécessitent des stratégies digitales différentes — visibilité saisonnière d''un côté, acquisition B2B de l''autre — que nous savons combiner efficacement.',
  'Oui, l''Agence HDS intervient à La Ciotat et sur le littoral entre Cassis et Bandol. Nous accompagnons les acteurs du tourisme, du nautisme et du commerce local dans leurs projets web, avec une approche adaptée aux spécificités de l''économie littorale.',
  'Agence Web La Ciotat — Création Site Internet | Agence HDS',
  'Agence web à La Ciotat. Sites internet pour tourisme, nautisme et commerce local. E-commerce et applications sur mesure. Devis gratuit — Agence HDS.',
  true
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  department = EXCLUDED.department,
  postal_code = EXCLUDED.postal_code,
  lat = EXCLUDED.lat,
  lng = EXCLUDED.lng,
  hero_title = EXCLUDED.hero_title,
  hero_subtitle = EXCLUDED.hero_subtitle,
  intro_paragraph = EXCLUDED.intro_paragraph,
  local_context = EXCLUDED.local_context,
  faq_answer = EXCLUDED.faq_answer,
  meta_title = EXCLUDED.meta_title,
  meta_description = EXCLUDED.meta_description,
  is_active = EXCLUDED.is_active,
  updated_at = now();
